version: '3.8'

services:
  postgres-authentication:
    image: postgres:15.8-alpine
    container_name: postgres-authentication
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - ./authentication-service/db/migrations/000001_create_users_table.up.sql:/docker-entrypoint-initdb.d/000001_create_users_table.up.sql

  postgres-orders-adresses:
    image: postgres:15.8-alpine
    container_name: postgres-orders-adresses
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: orders-adresses
    ports:
      - "5433:5432"
    volumes:
      - ./orders-service/db/migrations/000001_create_orders_table.up.sql:/docker-entrypoint-initdb.d/000001_create_users_orders.up.sql

  postgres-inventory:
    image: postgres:15.8-alpine
    container_name: postgres-inventory
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: product-inventory
    ports:
      - "5434:5432"
    volumes:
      - ./inventory-service/db/migrations/000001_add_inventory_table.up.sql:/docker-entrypoint-initdb.d/000001_add_inventory_table.up


  redis-cart:
    image: redis:latest
    container_name: redis-cart
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq-cart-orders:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.3
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
volumes: 
  redis_data:
  esdata:
