version: '3'
services:
  users-db:
    image: postgres:15.8-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: users
    ports:
      - "5432:5432"

    


  